// Generated by gencpp from file realsense_d435/objectionsofonemat.msg
// DO NOT EDIT!


#ifndef REALSENSE_D435_MESSAGE_OBJECTIONSOFONEMAT_H
#define REALSENSE_D435_MESSAGE_OBJECTIONSOFONEMAT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <realsense_d435/objection.h>
#include <sensor_msgs/PointCloud2.h>
#include <sensor_msgs/Image.h>

namespace realsense_d435
{
template <class ContainerAllocator>
struct objectionsofonemat_
{
  typedef objectionsofonemat_<ContainerAllocator> Type;

  objectionsofonemat_()
    : objectionsofonemat()
    , sizeofobjections(0)
    , pointcloud()
    , ImgRGB()  {
    }
  objectionsofonemat_(const ContainerAllocator& _alloc)
    : objectionsofonemat(_alloc)
    , sizeofobjections(0)
    , pointcloud(_alloc)
    , ImgRGB(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::realsense_d435::objection_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::realsense_d435::objection_<ContainerAllocator> >::other >  _objectionsofonemat_type;
  _objectionsofonemat_type objectionsofonemat;

   typedef uint8_t _sizeofobjections_type;
  _sizeofobjections_type sizeofobjections;

   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _pointcloud_type;
  _pointcloud_type pointcloud;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _ImgRGB_type;
  _ImgRGB_type ImgRGB;





  typedef boost::shared_ptr< ::realsense_d435::objectionsofonemat_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::realsense_d435::objectionsofonemat_<ContainerAllocator> const> ConstPtr;

}; // struct objectionsofonemat_

typedef ::realsense_d435::objectionsofonemat_<std::allocator<void> > objectionsofonemat;

typedef boost::shared_ptr< ::realsense_d435::objectionsofonemat > objectionsofonematPtr;
typedef boost::shared_ptr< ::realsense_d435::objectionsofonemat const> objectionsofonematConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::realsense_d435::objectionsofonemat_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::realsense_d435::objectionsofonemat_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::realsense_d435::objectionsofonemat_<ContainerAllocator1> & lhs, const ::realsense_d435::objectionsofonemat_<ContainerAllocator2> & rhs)
{
  return lhs.objectionsofonemat == rhs.objectionsofonemat &&
    lhs.sizeofobjections == rhs.sizeofobjections &&
    lhs.pointcloud == rhs.pointcloud &&
    lhs.ImgRGB == rhs.ImgRGB;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::realsense_d435::objectionsofonemat_<ContainerAllocator1> & lhs, const ::realsense_d435::objectionsofonemat_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace realsense_d435

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::realsense_d435::objectionsofonemat_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::realsense_d435::objectionsofonemat_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_d435::objectionsofonemat_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::realsense_d435::objectionsofonemat_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_d435::objectionsofonemat_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::realsense_d435::objectionsofonemat_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::realsense_d435::objectionsofonemat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c20814cdec399dd00db133a7fe620641";
  }

  static const char* value(const ::realsense_d435::objectionsofonemat_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc20814cdec399dd0ULL;
  static const uint64_t static_value2 = 0x0db133a7fe620641ULL;
};

template<class ContainerAllocator>
struct DataType< ::realsense_d435::objectionsofonemat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realsense_d435/objectionsofonemat";
  }

  static const char* value(const ::realsense_d435::objectionsofonemat_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::realsense_d435::objectionsofonemat_<ContainerAllocator> >
{
  static const char* value()
  {
    return "realsense_d435/objection[] objectionsofonemat\n"
"uint8 sizeofobjections\n"
"sensor_msgs/PointCloud2 pointcloud\n"
"sensor_msgs/Image ImgRGB\n"
"================================================================================\n"
"MSG: realsense_d435/objection\n"
"string classname\n"
"uint8  classID\n"
"geometry_msgs/Point center_point\n"
"geometry_msgs/Point32[] point_cloud\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"================================================================================\n"
"MSG: sensor_msgs/PointCloud2\n"
"# This message holds a collection of N-dimensional points, which may\n"
"# contain additional information such as normals, intensity, etc. The\n"
"# point data is stored as a binary blob, its layout described by the\n"
"# contents of the \"fields\" array.\n"
"\n"
"# The point cloud data may be organized 2d (image-like) or 1d\n"
"# (unordered). Point clouds organized as 2d images may be produced by\n"
"# camera depth sensors such as stereo or time-of-flight.\n"
"\n"
"# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n"
"# points).\n"
"Header header\n"
"\n"
"# 2D structure of the point cloud. If the cloud is unordered, height is\n"
"# 1 and width is the length of the point cloud.\n"
"uint32 height\n"
"uint32 width\n"
"\n"
"# Describes the channels and their layout in the binary data blob.\n"
"PointField[] fields\n"
"\n"
"bool    is_bigendian # Is this data bigendian?\n"
"uint32  point_step   # Length of a point in bytes\n"
"uint32  row_step     # Length of a row in bytes\n"
"uint8[] data         # Actual point data, size is (row_step*height)\n"
"\n"
"bool is_dense        # True if there are no invalid points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointField\n"
"# This message holds the description of one point entry in the\n"
"# PointCloud2 message format.\n"
"uint8 INT8    = 1\n"
"uint8 UINT8   = 2\n"
"uint8 INT16   = 3\n"
"uint8 UINT16  = 4\n"
"uint8 INT32   = 5\n"
"uint8 UINT32  = 6\n"
"uint8 FLOAT32 = 7\n"
"uint8 FLOAT64 = 8\n"
"\n"
"string name      # Name of field\n"
"uint32 offset    # Offset from start of point struct\n"
"uint8  datatype  # Datatype enumeration, see above\n"
"uint32 count     # How many elements in the field\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
;
  }

  static const char* value(const ::realsense_d435::objectionsofonemat_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::realsense_d435::objectionsofonemat_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.objectionsofonemat);
      stream.next(m.sizeofobjections);
      stream.next(m.pointcloud);
      stream.next(m.ImgRGB);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct objectionsofonemat_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::realsense_d435::objectionsofonemat_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::realsense_d435::objectionsofonemat_<ContainerAllocator>& v)
  {
    s << indent << "objectionsofonemat[]" << std::endl;
    for (size_t i = 0; i < v.objectionsofonemat.size(); ++i)
    {
      s << indent << "  objectionsofonemat[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::realsense_d435::objection_<ContainerAllocator> >::stream(s, indent + "    ", v.objectionsofonemat[i]);
    }
    s << indent << "sizeofobjections: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sizeofobjections);
    s << indent << "pointcloud: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.pointcloud);
    s << indent << "ImgRGB: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.ImgRGB);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REALSENSE_D435_MESSAGE_OBJECTIONSOFONEMAT_H
